// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 101,
    teacherId: "T1234",
    name: "Emily Chen",
    email: "emily.chen@educate.org",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-1234",
    subjects: ["CS", "Robotics"],
    classes: ["9A", "10B", "11C"],
    address: "456 Tech Ln, SV, CA",
  },
  {
    id: 102,
    teacherId: "T2345",
    name: "Marcus Johnson",
    email: "marcus.j@stemacademy.edu",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-9876",
    subjects: ["EnvSci", "Bio"],
    classes: ["7C", "8A", "9B"],
    address: "789 Green St, EC, OR",
  },
  {
    id: 103,
    teacherId: "T3456",
    name: "Sophia Patel",
    email: "s.patel@mathwhiz.net",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-2468",
    subjects: ["Calc", "Stats"],
    classes: ["11A", "12B", "AP"],
    address: "101 Pi Ave, NT, NY",
  },
  {
    id: 104,
    teacherId: "T4567",
    name: "Liam O'Connor",
    email: "liam.oconnor@historybufs.com",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-3697",
    subjects: ["History", "PolSci"],
    classes: ["10C", "11A", "12B"],
    address: "222 Time Blvd, PV, MA",
  },
  {
    id: 105,
    teacherId: "T5678",
    name: "Zoe Martinez",
    email: "zoe.m@artsacademy.org",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-7891",
    subjects: ["Art", "ArtHist"],
    classes: ["6B", "7A", "8C"],
    address: "333 Canvas Rd, PC, FL",
  },
  {
    id: 106,
    teacherId: "T6789",
    name: "Aiden Nguyen",
    email: "a.nguyen@sciencelab.edu",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-4567",
    subjects: ["Chem", "Physics"],
    classes: ["10A", "11B", "12C"],
    address: "444 Element Ave, RC, TX",
  },
  {
    id: 107,
    teacherId: "T7890",
    name: "Isabella Kim",
    email: "bella.kim@langlearn.net",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-8523",
    subjects: ["French", "German"],
    classes: ["8B", "9A", "10C"],
    address: "555 Poly St, LV, IL",
  },
  {
    id: 108,
    teacherId: "T8901",
    name: "Ethan Goldberg",
    email: "e.goldberg@mathgenius.com",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-1597",
    subjects: ["Algebra", "Trig"],
    classes: ["9C", "10A", "11B"],
    address: "666 Eq Ln, FF, NV",
  },
  {
    id: 109,
    teacherId: "T9012",
    name: "Olivia Thompson",
    email: "o.thompson@litlovers.org",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-9513",
    subjects: ["Writing", "Poetry"],
    classes: ["7B", "8A", "9C"],
    address: "777 Prose Rd, VV, WA",
  },
  {
    id: 110,
    teacherId: "T0123",
    name: "Noah Rodriguez",
    email: "noah.r@sportsedu.net",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-2581",
    subjects: ["PE", "Health"],
    classes: ["6A", "7C", "8B"],
    address: "888 Fit Way, AT, AZ",
  },
];
export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Science Fair",
    class: "All",
    date: "2024-09-20",
    startTime: "09:00",
    endTime: "15:00",
  },
  {
    id: 2,
    title: "Parent-Teacher Conference",
    class: "All",
    date: "2024-09-25",
    startTime: "16:00",
    endTime: "20:00",
  },
  {
    id: 3,
    title: "Field Trip to Natural History Museum",
    class: "6A",
    date: "2024-10-05",
    startTime: "09:00",
    endTime: "15:00",
  },
  {
    id: 4,
    title: "Annual Sports Day",
    class: "All",
    date: "2024-10-15",
    startTime: "08:00",
    endTime: "16:00",
  },
  {
    id: 5,
    title: "School Play: Romeo and Juliet",
    class: "9B",
    date: "2024-11-10",
    startTime: "18:00",
    endTime: "20:00",
  },
  {
    id: 6,
    title: "Career Day",
    class: "11A, 11B, 12A, 12B",
    date: "2024-11-20",
    startTime: "10:00",
    endTime: "14:00",
  },
  {
    id: 7,
    title: "Winter Concert",
    class: "All",
    date: "2024-12-15",
    startTime: "18:00",
    endTime: "20:00",
  },
  {
    id: 8,
    title: "Debate Competition",
    class: "10A, 10B",
    date: "2025-01-20",
    startTime: "13:00",
    endTime: "16:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "All",
    date: "2025-02-05",
    startTime: "10:00",
    endTime: "15:00",
  },
  {
    id: 10,
    title: "Graduation Ceremony",
    class: "12A, 12B",
    date: "2025-06-15",
    startTime: "10:00",
    endTime: "12:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "New Library Hours",
    class: "All",
    date: "2024-09-18",
  },
  {
    id: 2,
    title: "Student Council Elections",
    class: "9A, 9B, 10A, 10B, 11A, 11B",
    date: "2024-09-22",
  },
  {
    id: 3,
    title: "Flu Shot Clinic",
    class: "All",
    date: "2024-10-01",
  },
  {
    id: 4,
    title: "SAT Prep Course Registration",
    class: "11A, 11B, 12A, 12B",
    date: "2024-10-05",
  },
  {
    id: 5,
    title: "Yearbook Photo Schedule",
    class: "All",
    date: "2024-10-10",
  },
  {
    id: 6,
    title: "Bake Sale for Charity",
    class: "All",
    date: "2024-10-20",
  },
  {
    id: 7,
    title: "College Application Workshop",
    class: "12A, 12B",
    date: "2024-11-05",
  },
  {
    id: 8,
    title: "Holiday Food Drive",
    class: "All",
    date: "2024-12-01",
  },
  {
    id: 9,
    title: "Spring Sports Tryouts",
    class: "9A, 9B, 10A, 10B, 11A, 11B",
    date: "2025-02-15",
  },
  {
    id: 10,
    title: "Summer School Registration",
    class: "All",
    date: "2025-05-01",
  },
];

export const calendarEvents = [
  {
    title: "Algebra II",
    allDay: false,
    start: new Date(2024, 8, 16, 8, 0),
    end: new Date(2024, 8, 16, 8, 50),
  },
  {
    title: "English Literature",
    allDay: false,
    start: new Date(2024, 8, 16, 9, 0),
    end: new Date(2024, 8, 16, 9, 50),
  },
  {
    title: "Chemistry Lab",
    allDay: false,
    start: new Date(2024, 8, 16, 10, 0),
    end: new Date(2024, 8, 16, 11, 40),
  },
  {
    title: "Lunch Break",
    allDay: false,
    start: new Date(2024, 8, 16, 11, 45),
    end: new Date(2024, 8, 16, 12, 30),
  },
  {
    title: "World History",
    allDay: false,
    start: new Date(2024, 8, 16, 12, 35),
    end: new Date(2024, 8, 16, 13, 25),
  },
  {
    title: "Physical Education",
    allDay: false,
    start: new Date(2024, 8, 16, 13, 30),
    end: new Date(2024, 8, 16, 14, 20),
  },
  {
    title: "Spanish II",
    allDay: false,
    start: new Date(2024, 8, 16, 14, 25),
    end: new Date(2024, 8, 16, 15, 15),
  },
  {
    title: "Computer Science",
    allDay: false,
    start: new Date(2024, 8, 17, 8, 0),
    end: new Date(2024, 8, 17, 8, 50),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 8, 17, 9, 0),
    end: new Date(2024, 8, 17, 9, 50),
  },
  {
    title: "Art",
    allDay: false,
    start: new Date(2024, 8, 17, 10, 0),
    end: new Date(2024, 8, 17, 11, 40),
  },
  {
    title: "Lunch Break",
    allDay: false,
    start: new Date(2024, 8, 17, 11, 45),
    end: new Date(2024, 8, 17, 12, 30),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 8, 17, 12, 35),
    end: new Date(2024, 8, 17, 13, 25),
  },
  {
    title: "Economics",
    allDay: false,
    start: new Date(2024, 8, 17, 13, 30),
    end: new Date(2024, 8, 17, 14, 20),
  },
  {
    title: "Music",
    allDay: false,
    start: new Date(2024, 8, 17, 14, 25),
    end: new Date(2024, 8, 17, 15, 15),
  },
];